###############################################
#       _______  _______  _______
#     |__   __||  ___  ||  ___  |
#       | |   | |___| || |___| |
#      | |   |  _____||  ___  |
#     | |   | |      | |   | |
#    |_|   |_|      |_|   |_|     by l4zs
##############################################

# When tpa requests should expire (in seconds)
# This is used to prevent abuse of the TPA system
# Set to 0 to disable
request_expire: 60

disabled_worlds:
  tpa:
    # Worlds to disable teleporting to
    to:
      - "disabledWorld"

    # Worlds to disable teleporting from
    from:
      - "disabledWorld"

    # Worlds to allow teleporting to if the players are in the same world (you may add "*" to allow all worlds)
    allow_if_same_world:
      - "allowedWorld"

  # Worlds to disable going back to
  back:
    - "disabledWorld"

# Allows you disable the following commands, you'll have to restart the server to apply the changes:
# /back
# /tpaccept
# /tpa
# /tpahereall
# /tpahere
# /tpcancel
# /tpdeny
# /tptoggle
# i.E if you want to disable the /tpa command, add "tpa" to the list
# Keep in mind that disabling the /tpa command will also disable the reload (config and translations) literals associated with it
disabled_commands:
  - "disabledCommand"
