###############################################
#       _______  _______  _______
#     |__   __||  ___  ||  ___  |
#       | |   | |___| || |___| |
#      | |   |  _____||  ___  |
#     | |   | |      | |   | |
#    |_|   |_|      |_|   |_|     by l4zs
##############################################



# Path: translations
# The enabled translations
# The first one will be used as a fallback and therefore must be complete
# (all keys set, like in the English translation)
#
# Add as many translations as you want (create a new file for each)
# i.e. 'general_fr.properties' for French
# The file must be named as the language code (2 characters)
# Then add the language code to this list
translations:
  - "en"
  - "de"

# When tpa requests should expire (in seconds)
request_expire: 60

disabled_worlds:
  # Worlds to disable teleporting to
  to:
    - "disabledWorld"
  # Worlds to disable teleporting from
  from:
    - "disabledWorld"
  # Worlds to allow teleporting to if the players are in the same world (you may add "*" to allow all worlds)
  allow_if_same_world:
    - "allowedWorld"
